### ISSUE TITLE
Import videos

### ISSUE THREAD

**Issue by deedos** [nebulabroadcast/nebula#1]
First at all, many thanks for the really nice project!
I have managed to install alongside nebula-setup and Firefly.  I have doubts about how to ingest/import the video files. I did suceed setting up a watch service and the Assets are created but none of them are accessible on Firefly.
What am I missing ?

Many thanks again

**Comment by martastain** [comment]
Hello Daniel,
since you are the first who managed to get so far even though the documentation is far from complete, we should send you a T-Shirt or something :). By default, "watch" service creates assets in "Incoming" folder, so if you have Firefly up and running, you should see them if you switch to incoming view using a drop-down menu next to the search button. 

Unfortunately, the view for "incoming" assets is missing in the default configuration (my bad - sorry - i'll fix it in the following update), but you can simply add it in your template file:

```python
data["views"][13] = {
    "title" : "Incoming",
    "position" : 13,
    "folders" : [12], 
    "columns" : [
        "qc/state",
        "title",
        "duration",
        "mtime"
    ]
}
```

After you rewrite your configuration, restart the hub service and firefly and you should be able to see your assets (without video preview - I need to document the process of creating lowres proxy files, so please stay tuned).

**Comment by deedos** [comment]
Hi  @martastain . Thanks, I'll accept the T-shirt ;) The workaround woks and I can see my assets both on Firefly and nebula-frontend, really nice! Next step is to be able to play the media...Could you help me with that ? CasparCG is running (version 2.2 Beta)
thanks and once again, congrats fo the great work!

**Comment by michaeltoohig** [comment]
@deedos did you get the media to play? I'm slowing making progress getting my config to work but no success with Firefly yet. Wondering if I should continue to figure this out or try out some others in the meantime.
