### ISSUE TITLE
Samba Issues

### ISSUE THREAD

**Issue by michaeltoohig** [nebulabroadcast/nebula#5]
I've tried setting up a Samba server on the local machine and a remote machine which I can connect to independently but Nebula has failed to connect.

I set my storages to `local` and then I had success. But following what happened in #1 I don't see my assets automatically loaded when I dump files in the `local` storage. So not sure if `local` files are supported yet.

**Comment by martastain** [comment]
Local storages are intended for situations you want to handle mounting filesystems outside Nebula. It is still expected the location is `/mnt/{sitename}_{id_storage}`. 

Connections problems are usually caused by samba protocol version - depending on your storage server, you might to try set `samba_version` parameter to `"1.0"` or `"2.0"` in your storage definition (default is "3.0"). 

Nebula uses `mount.cifs` to mount the storages. Try to execute the command directly to see, what is wrong:

`mount.cifs //SERVER/SHARE /mnt/nebula_01 -o 'user=USER,pass=PASSWORD,vers=2.0'`

If your storage is windows based, tweaking server registry may also help:

In `HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management`, set the `LargeSystemCache` key to `1` (hex).

In `HKLM\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters`, set the `Size` key to `3` (hex).’

**Comment by michaeltoohig** [comment]
Adding those extra options to `storages` seems to have worked. I still see an error in nebula about `cifs` even though I have installed `cifs-utils`.

```
2019-05-31 16:07:32 DEBUG       nebula          mount.cifs : /bin/sh: 1: mount.cifs: not found
```

Although I do see the mounted storages now.
