### ISSUE TITLE
database connection error

### ISSUE THREAD

**Issue by sfahadshahzad** [nebulabroadcast/nebula#6]
Hi,

got database connection error upon running ./manage.py adduser.

Regards,

Fahad

**Comment by martastain** [comment]
Try to connect the database using psql command with the same credentials you provided in the settings.json file. My wild guess is this is caused by misconfigured DB server. Please consult PostgreSQL documentation and check that database structure has been created during setup (for example querying "SELECT * FROM meta_types").

**Comment by sfahadshahzad** [comment]
I did not changed the settings.json

**Comment by martastain** [comment]
Added `create_db.sh` description to nebula-setup/README.md :)
